<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            'Avganistan',
            'Albanija',
            'Alžir',
            'Andora',
            'Angola',
            'Antigua i Barbuda',
            'Argentina',
            'Australija',
            'Austrija',
            'Azerbajdžan',
            'Bahami',
            'Bahrein',
            'Bangladeš',
            'Barbados',
            'Belgija',
            'Belize',
            'Benin',
            'Belorusija',
            'Bocvana',
            'Bolivija',
            'Bosna i Hercegovina',
            'Brazil',
            'Brunej',
            'Bugarska',
            'Burkina Faso',
            'Burundi',
            'Butan',
            'Crna Gora',
            'Čad',
            'Češka',
            'Čile',
            'Danska',
            'Demokratska Republika Kongo',
            'Dominika',
            'Dominikanska Republika',
            'Džibuti',
            'Egipat',
            'Ekvador',
            'Ekvatorijalna Gvineja',
            'Eritreja',
            'Estonija',
            'Etiopija',
            'Fidži',
            'Filipini',
            'Finska',
            'Francuska',
            'Gabon',
            'Gambija',
            'Gana',
            'Grčka',
            'Grenada',
            'Gruzija',
            'Gvajana',
            'Gvatemala',
            'Gvineja Bisau',
            'Gvineja',
            'Haiti',
            'Holandija',
            'Honduras',
            'Hrvatska',
            'Indija',
            'Indonezija',
            'Irak',
            'Iran',
            'Irska',
            'Island',
            'Istočni Timor',
            'Italija',
            'Izrael',
            'Jamajka',
            'Japan',
            'Jemen',
            'Jermenija',
            'Jordan',
            'Južna Afrika',
            'Južna Koreja',
            'Južni Sudan',
            'Kambodža',
            'Kamerun',
            'Kanada',
            'Katar',
            'Kazahstan',
            'Kenija',
            'Kina',
            'Kipar',
            'Kirgistan',
            'Kiribati',
            'Kolumbija',
            'Komori',
            'Kongo',
            'Kostarika',
            'Kraljevina Eswatini',
            'Kuba',
            'Kuvajt',
            'Laos',
            'Lesoto',
            'Letonija',
            'Liban',
            'Liberija',
            'Libija',
            'Lihtenštajn',
            'Litvanija',
            'Luksemburg',
            'Madagaskar',
            'Mađarska',
            'Malavi',
            'Maldivi',
            'Malezija',
            'Mali',
            'Malta',
            'Maroko',
            'Maršalovska ostrva',
            'Mauricijus',
            'Mauritanija',
            'Meksiko',
            'Mjanmar (Burma)',
            'Moldavija',
            'Monako',
            'Mongolija',
            'Mozambik',
            'Namibija',
            'Nauru',
            'Nepal',
            'Niger',
            'Nigerija',
            'Nikaragva',
            'Norveška',
            'Novi Zeland',
            'Nemačka',
            'Obala Slonovače',
            'Oman',
            'Pakistan',
            'Palau',
            'Palestina',
            'Panama',
            'Papua Nova Gvineja',
            'Paragvaj',
            'Peru',
            'Poljska',
            'Portugal',
            'Republika Centralna Afrika',
            'Ruanda',
            'Rumunija',
            'Rusija',
            'Salvador',
            'Samoa',
            'San Marino',
            'Saudijska Arabija',
            'Savezne Države Mikronezije',
            'Sejšeli',
            'Senegal',
            'Severna Koreja',
            'Severna Makedonija',
            'Sijera Leone',
            'Singapur',
            'Sirija',
            'Sjedinjene Američke Države',
            'Slovačka',
            'Slovenija',
            'Solomonovska ostrva',
            'Somalija',
            'Srbija',
            'Sudan',
            'Surinam',
            'Sveta Lucija',
            'Sveti Kristofor i Nevis',
            'Sveti Toma i Princip',
            'Sveti Vincent i Grenadini',
            'Španija',
            'Šri Lanka',
            'Švedska',
            'Švajcarska',
            'Tadžikistan',
            'Tajland',
            'Tanzanija',
            'Togo',
            'Tonga',
            'Trinidad i Tobago',
            'Tunis',
            'Turkmenistan',
            'Turska',
            'Tuvalu',
            'Uganda',
            'Ujedinjeni Arapski Emirati',
            'Ujedinjeno Kraljevstvo',
            'Ukrajina',
            'Urugvaj',
            'Uzbekistan',
            'Vanuatu',
            'Vatikan',
            'Venecuela',
            'Vijetnam',
            'Zambija',
            'Zelenortska Ostrva',
            'Zimbabve',
        ];

        foreach ($countries as $country) {
            Country::create([
                'title' => $country,
            ]);
        }
    }
}
